# GitHub presets
safe: true
lsi: false

# custom settings
author: Matt Ross
author_email: matt@mattross.io
description: method collective
destination: ./_site
exclude:
  - package.json
  - Gruntfile.js
  - node_modules
  - README.md
gems:
  - jekyll-sitemap
keys:
  ga: false
name: METHOD COLLECTIVE
permalink: pretty
source: .
timezone: America/New_York
url: http://www.methodcollective.com
