# GitHub presets
safe: true
lsi: false

# custom settings
author: Matt Ross
author_email: matt@mattross.io
description: brick and mortar
destination: ./_site
exclude:
  - package.json
  - Gruntfile.js
  - node_modules
  - README.md
gems:
  - jekyll-sitemap
keys:
  ga: false
name: BRICK AND MORTAR
permalink: pretty
source: .
timezone: America/New_York
url: http://www.brickandmortarphilly.com
